/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BD.Funciones;
import javax.swing.JOptionPane;

/**
 *
 * @author neyra
 */
public class Pan_Desvincular extends javax.swing.JPanel {
    String rut, digito;
    /**
     * Creates new form Pan_Desvincular
     */
    public Pan_Desvincular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_TomaFoto = new javax.swing.JButton();
        Txt_Digito = new javax.swing.JTextField();
        Lbl_Funcion = new javax.swing.JLabel();
        Pan_Foto = new javax.swing.JPanel();
        Lbl_Supervisor = new javax.swing.JLabel();
        Txt_PriNomn = new javax.swing.JTextField();
        Cbx_Departamento = new javax.swing.JComboBox<>();
        Txt_SegNom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Txt_PriApe = new javax.swing.JTextField();
        Cbx_Funcion = new javax.swing.JComboBox<>();
        Txt_SegApe = new javax.swing.JTextField();
        Cbx_Supervisor = new javax.swing.JComboBox<>();
        Lbl_Titulo = new javax.swing.JLabel();
        lbl_PRiNomn = new javax.swing.JLabel();
        Btn_Cancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Lbl_SegNom = new javax.swing.JLabel();
        Btn_Desvincular = new javax.swing.JButton();
        Lbl_Rut = new javax.swing.JLabel();
        Lbl_PriApe = new javax.swing.JLabel();
        Txt_Rut = new javax.swing.JTextField();
        Lbl_SegApe = new javax.swing.JLabel();
        Lbl_Guion = new javax.swing.JLabel();
        Btn_Buscar = new javax.swing.JButton();

        Btn_TomaFoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_TomaFoto.setText("Captura Fotografía");

        Txt_Digito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_Digito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_DigitoFocusLost(evt);
            }
        });
        Txt_Digito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_DigitoKeyTyped(evt);
            }
        });

        Lbl_Funcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Funcion.setText("Función:");

        Pan_Foto.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout Pan_FotoLayout = new javax.swing.GroupLayout(Pan_Foto);
        Pan_Foto.setLayout(Pan_FotoLayout);
        Pan_FotoLayout.setHorizontalGroup(
            Pan_FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );
        Pan_FotoLayout.setVerticalGroup(
            Pan_FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        Lbl_Supervisor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Supervisor.setText("Supervisor:");

        Txt_PriNomn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Cbx_Departamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cbx_Departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Txt_SegNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Departamento:");

        Txt_PriApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Cbx_Funcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cbx_Funcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Txt_SegApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Cbx_Supervisor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cbx_Supervisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Lbl_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Lbl_Titulo.setText("Datos de Empleado:");

        lbl_PRiNomn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_PRiNomn.setText("Primer Nombre:");

        Btn_Cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_Cancelar.setText("Cancelar");

        Lbl_SegNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_SegNom.setText("Segundo Nombre:");

        Btn_Desvincular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_Desvincular.setText("Eliminar");

        Lbl_Rut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Rut.setText("Rut:");

        Lbl_PriApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_PriApe.setText("Primer Apellido:");

        Txt_Rut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_Rut.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txt_Rut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_RutFocusLost(evt);
            }
        });
        Txt_Rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_RutKeyTyped(evt);
            }
        });

        Lbl_SegApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_SegApe.setText("Segundo Apellido:");

        Lbl_Guion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Guion.setText("-");

        Btn_Buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_Buscar.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_Titulo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_Rut)
                                .addGap(269, 269, 269)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Txt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Lbl_Guion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Txt_Digito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Txt_PriNomn)
                                    .addComponent(Txt_SegNom)
                                    .addComponent(Txt_PriApe)
                                    .addComponent(Txt_SegApe, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(Btn_Buscar))
                            .addComponent(lbl_PRiNomn)
                            .addComponent(Lbl_SegNom)
                            .addComponent(Lbl_PriApe)
                            .addComponent(Lbl_SegApe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_Desvincular))
                            .addComponent(Btn_TomaFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Pan_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_Supervisor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cbx_Supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(169, 169, 169)
                                .addComponent(Cbx_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_Funcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cbx_Funcion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pan_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_TomaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Cancelar)
                            .addComponent(Btn_Desvincular))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_PRiNomn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_Guion)
                                    .addComponent(Txt_Digito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Buscar)
                                    .addComponent(Lbl_Rut))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_PriNomn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_SegNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_SegNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_PriApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_PriApe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_SegApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_SegApe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Cbx_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_Funcion)
                            .addComponent(Cbx_Funcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_Supervisor)
                            .addComponent(Cbx_Supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_RutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_RutFocusLost
        rut = Txt_Rut.getText();
        Txt_Rut.setText(Funciones.formateo_Rut(rut));
    }//GEN-LAST:event_Txt_RutFocusLost

    private void Txt_DigitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_DigitoFocusLost
        Txt_Digito.setText(Txt_Digito.getText().toUpperCase());
        rut=Txt_Rut.getText();
        digito = Funciones.digito(rut);
        if (!Txt_Digito.getText().equals(digito)){
            //JOptionPane.showConfirmDialog(this, "RUT ingresado no es valido, favor de verificar los datos");
            JOptionPane.showMessageDialog(this, "RUT ingresado no es valido, favor de verificar los datos");
            Txt_Rut.setText("");
            Txt_Digito.setText("");
            Txt_Rut.requestFocus();
        }
    }//GEN-LAST:event_Txt_DigitoFocusLost

    private void Txt_RutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_RutKeyTyped
        //valida que solo se ingresen números y sognos de puntuación
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <=57 || key == 44 || key == 46 ;
        if(!numeros){
            evt.consume();
        }
    }//GEN-LAST:event_Txt_RutKeyTyped

    private void Txt_DigitoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_DigitoKeyTyped
        //valida que solo se ingresen números y letra K (mayuscula o minuscula)
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <=57 || key == 75 || key == 107 ;
        if(!numeros){
            evt.consume();
        }
    }//GEN-LAST:event_Txt_DigitoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Desvincular;
    private javax.swing.JButton Btn_TomaFoto;
    private javax.swing.JComboBox<String> Cbx_Departamento;
    private javax.swing.JComboBox<String> Cbx_Funcion;
    private javax.swing.JComboBox<String> Cbx_Supervisor;
    private javax.swing.JLabel Lbl_Funcion;
    private javax.swing.JLabel Lbl_Guion;
    private javax.swing.JLabel Lbl_PriApe;
    private javax.swing.JLabel Lbl_Rut;
    private javax.swing.JLabel Lbl_SegApe;
    private javax.swing.JLabel Lbl_SegNom;
    private javax.swing.JLabel Lbl_Supervisor;
    private javax.swing.JLabel Lbl_Titulo;
    private javax.swing.JPanel Pan_Foto;
    private javax.swing.JTextField Txt_Digito;
    private javax.swing.JTextField Txt_PriApe;
    private javax.swing.JTextField Txt_PriNomn;
    private javax.swing.JTextField Txt_Rut;
    private javax.swing.JTextField Txt_SegApe;
    private javax.swing.JTextField Txt_SegNom;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_PRiNomn;
    // End of variables declaration//GEN-END:variables
}
