/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BD.Funciones;
import static BD.Funciones.Panell;
import static BD.Funciones.mostrarImagen;
import static BD.Funciones.startCamera;
import BD.SQL_Metodos;
import BD.Persona;
import static BD.Persona.imagen1;
import static BD.Persona.manipular_byte;
import java.awt.event.ItemEvent;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.opencv.core.Core;

/**
 *
 * @author neyra
 */
public class Pan_Actualizar extends javax.swing.JPanel {
    
    public SQL_Metodos sQL_Metodos = new SQL_Metodos();
    String rut, digito, pnombre, snombre, papellido, sapellido;
    Persona persona = new Persona();
    
    /**
     * Creates new form Pan_Actualizar
     */
    public Pan_Actualizar() {
        initComponents();
        Txt_Rut.requestFocus();
		jButton_Foto1.setEnabled(false);
        jButton3_Foto3.setEnabled(false);
        jButton2_Foto2.setEnabled(false);
        Btn_Cancelar.setEnabled(false);
        Cbx_Departamento.removeAllItems();
        Cbx_Funcion.removeAllItems();
        llenaComboDepto();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cbx_Funcion = new javax.swing.JComboBox<>();
        Txt_SegApe = new javax.swing.JTextField();
        Cbx_Supervisor = new javax.swing.JComboBox<>();
        Lbl_Titulo = new javax.swing.JLabel();
        lbl_PRiNomn = new javax.swing.JLabel();
        Btn_Cancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Lbl_SegNom = new javax.swing.JLabel();
        Btn_Actualizar = new javax.swing.JButton();
        Lbl_Rut = new javax.swing.JLabel();
        Btn_TomaFoto = new javax.swing.JButton();
        Txt_Digito = new javax.swing.JTextField();
        Lbl_Funcion = new javax.swing.JLabel();
        Pan_Foto = new javax.swing.JPanel();
        Lbl_Supervisor = new javax.swing.JLabel();
        Txt_PriNomn = new javax.swing.JTextField();
        Cbx_Departamento = new javax.swing.JComboBox<>();
        Txt_SegNom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Txt_PriApe = new javax.swing.JTextField();
        Lbl_PriApe = new javax.swing.JLabel();
        Txt_Rut = new javax.swing.JTextField();
        Lbl_SegApe = new javax.swing.JLabel();
        Lbl_Guion = new javax.swing.JLabel();
        Btn_Buscar = new javax.swing.JButton();
        jButton_Foto1 = new javax.swing.JButton();
        jButton3_Foto3 = new javax.swing.JButton();
        jButton2_Foto2 = new javax.swing.JButton();

        Cbx_Funcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cbx_Funcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Txt_SegApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_SegApe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_SegApeFocusLost(evt);
            }
        });

        Cbx_Supervisor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cbx_Supervisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Lbl_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Lbl_Titulo.setText("Datos de Empleado:");

        lbl_PRiNomn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_PRiNomn.setText("Primer Nombre:");

        Btn_Cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });

        Lbl_SegNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_SegNom.setText("Segundo Nombre:");

        Btn_Actualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_Actualizar.setText("Actualizar");
        Btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActualizarActionPerformed(evt);
            }
        });

        Lbl_Rut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Rut.setText("Rut:");

        Btn_TomaFoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_TomaFoto.setText("Captura Fotografía");
        Btn_TomaFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TomaFotoActionPerformed(evt);
            }
        });

        Txt_Digito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_Digito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_DigitoFocusLost(evt);
            }
        });
        Txt_Digito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_DigitoKeyTyped(evt);
            }
        });

        Lbl_Funcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Funcion.setText("Función:");

        Pan_Foto.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout Pan_FotoLayout = new javax.swing.GroupLayout(Pan_Foto);
        Pan_Foto.setLayout(Pan_FotoLayout);
        Pan_FotoLayout.setHorizontalGroup(
            Pan_FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );
        Pan_FotoLayout.setVerticalGroup(
            Pan_FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        Lbl_Supervisor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Supervisor.setText("Supervisor:");

        Txt_PriNomn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_PriNomn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_PriNomnFocusLost(evt);
            }
        });

        Cbx_Departamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cbx_Departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cbx_Departamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cbx_DepartamentoItemStateChanged(evt);
            }
        });

        Txt_SegNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Departamento:");

        Txt_PriApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_PriApe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_PriApeFocusLost(evt);
            }
        });

        Lbl_PriApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_PriApe.setText("Primer Apellido:");

        Txt_Rut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_Rut.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txt_Rut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_RutFocusLost(evt);
            }
        });
        Txt_Rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_RutKeyTyped(evt);
            }
        });

        Lbl_SegApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_SegApe.setText("Segundo Apellido:");

        Lbl_Guion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Guion.setText("-");

        Btn_Buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_Buscar.setText("Buscar");
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });

        jButton_Foto1.setText("Foto 1");
        jButton_Foto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Foto1ActionPerformed(evt);
            }
        });

        jButton3_Foto3.setText("Foto 3");
        jButton3_Foto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_Foto3ActionPerformed(evt);
            }
        });

        jButton2_Foto2.setText("Foto 2");
        jButton2_Foto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_Foto2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_Titulo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Lbl_Supervisor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Cbx_Supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(169, 169, 169)
                                        .addComponent(Cbx_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Lbl_Funcion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Cbx_Funcion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2_Foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3_Foto3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Lbl_Rut)
                                        .addGap(269, 269, 269)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Txt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Lbl_Guion)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Txt_Digito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Txt_PriNomn)
                                            .addComponent(Txt_SegNom)
                                            .addComponent(Txt_PriApe)
                                            .addComponent(Txt_SegApe, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addComponent(Btn_Buscar))
                                    .addComponent(lbl_PRiNomn)
                                    .addComponent(Lbl_SegNom)
                                    .addComponent(Lbl_PriApe)
                                    .addComponent(Lbl_SegApe))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn_Cancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_Actualizar))
                                    .addComponent(Btn_TomaFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Pan_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pan_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_TomaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Foto1)
                            .addComponent(jButton3_Foto3)
                            .addComponent(jButton2_Foto2))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Cancelar)
                            .addComponent(Btn_Actualizar))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_PRiNomn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_Guion)
                                    .addComponent(Txt_Digito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Buscar)
                                    .addComponent(Lbl_Rut))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_PriNomn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_SegNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_SegNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_PriApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_PriApe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_SegApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_SegApe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Cbx_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_Funcion)
                            .addComponent(Cbx_Funcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_Supervisor)
                            .addComponent(Cbx_Supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_RutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_RutFocusLost
        //Formatea el RUT según sea requerido
        rut = Txt_Rut.getText();
        Txt_Rut.setText(Funciones.formateo_Rut(rut));
        Btn_Cancelar.setEnabled(true); 
    }//GEN-LAST:event_Txt_RutFocusLost

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
        // TODO metodo para buscar los datos del empleado y cargarlos en los distintos objetos del formulario:
        int rutbuscar;
        rutbuscar = parseInt(Txt_Rut.getText());
        Persona personaSQL = sQL_Metodos.consultaEmpleado(rutbuscar);
        Txt_Digito.setText(personaSQL.getVerificador());
        Txt_PriNomn.setText(personaSQL.getPrimerNombre());
        Txt_SegNom.setText(personaSQL.getSegundoNombre());
        Txt_PriApe.setText(personaSQL.getPrimerApellido());
        Txt_SegApe.setText(personaSQL.getSegundoApellido());
        
        try {
            mostrarImagen(Pan_Foto, personaSQL.getImagen1());
            
        } catch (IOException ex) {
            Logger.getLogger(Pan_Actualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
         //Limpia todo el formulario preparandolo para el ingreso de nueva información
        Txt_Rut.setText("");
        Txt_Digito.setText("");
        Txt_PriNomn.setText("");
        Txt_SegNom.setText("");
        Txt_PriApe.setText("");
        Txt_SegApe.setText("");
        Cbx_Departamento.removeAllItems();
        Cbx_Funcion.removeAllItems();
        Cbx_Supervisor.removeAllItems();
        llenaComboDepto();
        Txt_Rut.requestFocus();
        Btn_Cancelar.setEnabled(false);
    }//GEN-LAST:event_Btn_CancelarActionPerformed

    private void Btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActualizarActionPerformed
        // TODO Metodo para almacenar los datos del usuario, debe enviar mensaje de confirmación luego de una actualización exitosa, limpia el formulario al terminar y coloca el foco en Txt_Rut:
        
    }//GEN-LAST:event_Btn_ActualizarActionPerformed

    private void Btn_TomaFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TomaFotoActionPerformed
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        startCamera();
        Panell = Pan_Foto;
        jButton_Foto1.setEnabled(true);
        jButton3_Foto3.setEnabled(true);
        jButton2_Foto2.setEnabled(true);
    }//GEN-LAST:event_Btn_TomaFotoActionPerformed

    private void Txt_DigitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_DigitoFocusLost
       //Calcula y valida el Digito Verificador del RUT
        Txt_Digito.setText(Txt_Digito.getText().toUpperCase());
        rut=Txt_Rut.getText();
        digito = Funciones.digito(rut);
        if (!Txt_Digito.getText().equals(digito)){
            JOptionPane.showMessageDialog(this, "RUT ingresado no es valido, favor de verificar los datos");
            Txt_Rut.setText("");
            Txt_Digito.setText("");
            Txt_Rut.requestFocus();
        }
    }//GEN-LAST:event_Txt_DigitoFocusLost

    private void Txt_RutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_RutKeyTyped
        //valida que solo se ingresen números y signos de puntuación
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <=57 || key == 44 || key == 46 ;
        if(!numeros){
            evt.consume();
        }
    }//GEN-LAST:event_Txt_RutKeyTyped

    private void Txt_DigitoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_DigitoKeyTyped
        //valida que solo se ingresen números y letra K (mayuscula o minuscula)
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <=57 || key == 75 || key == 107 ;
        if(!numeros){
            evt.consume();
        }
    }//GEN-LAST:event_Txt_DigitoKeyTyped

    private void Txt_PriNomnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_PriNomnFocusLost
        //Valida que el campo de texto asiciado el Primer Nombre no se encuentre vacio
        pnombre= Txt_PriNomn.getText();
        if ("".equals(Txt_Digito.getText())){  
            Txt_Digito.requestFocus();
        }
        else{
            if ("".equals(pnombre)){
                JOptionPane.showMessageDialog(this, "Debe ingresar el Primer Nombre del Colaborador");
                Txt_PriNomn.requestFocus();
            }
        }
    }//GEN-LAST:event_Txt_PriNomnFocusLost

    private void Txt_PriApeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_PriApeFocusLost
        //Valida que el campo de texto asiciado el Primer Apellido no se encuentre vacio
        papellido= Txt_PriApe.getText();
        if ("".equals(Txt_PriNomn.getText())){
            Txt_PriNomn.requestFocus();
        }
        else{
            if("".equals(papellido)){
                JOptionPane.showMessageDialog(this, "Debe ingresar el Primer Apellido del Colaborador");
                Txt_PriApe.requestFocus();
            }
        }
    }//GEN-LAST:event_Txt_PriApeFocusLost

    private void Txt_SegApeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_SegApeFocusLost
        //Valida que el campo de texto asiciado el Segundo Apellido no se encuentre vacio
        sapellido=Txt_SegApe.getText();
        if ("".equals(Txt_PriApe.getText())){
            Txt_PriApe.requestFocus();
        }
        else{
            if ("".equals(sapellido)){
                JOptionPane.showMessageDialog(this, "Debe ingresar el Segundo Apellido del Colaborador");
                Txt_SegApe.requestFocus();
            }
        }
    }//GEN-LAST:event_Txt_SegApeFocusLost

    private void Cbx_DepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {                                                  
        //Llena la información de los Combobox de cargos y supervisores según el departamento seleccionado
        ArrayList<String> cargo = new ArrayList<>();
        ArrayList<String> supervisor = new ArrayList<>();
        Cbx_Funcion.removeAllItems();
        Cbx_Funcion.addItem("");
        Cbx_Supervisor.removeAllItems();
        Cbx_Supervisor.addItem("");
        String aux;
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(Cbx_Departamento.getSelectedIndex()>0){
                aux=Cbx_Departamento.getSelectedItem().toString();
                cargo=sQL_Metodos.llenaCargo(aux);
                for (int i=0; i<cargo.size(); i++){
                    Cbx_Funcion.addItem(cargo.get(i));
                }
                supervisor=sQL_Metodos.llenaSupervisor(aux);
                for (int i=0; i<supervisor.size();i++ ){
                    Cbx_Supervisor.addItem(supervisor.get(i));
                }
            }
        }
    }
    
	private void jButton_Foto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Foto1ActionPerformed
            // TODO add your handling code here: 
            if (manipular_byte != null) {
                persona.setImagen1(manipular_byte);
                JOptionPane.showMessageDialog(null, "Primera Fotografía del colaborador Capturada");
            }

    }//GEN-LAST:event_jButton_Foto1ActionPerformed

    private void jButton2_Foto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Foto2ActionPerformed
        // TODO add your handling code here:
        if (manipular_byte != null) {
            persona.setImagen2(manipular_byte);
            JOptionPane.showMessageDialog(null, "Segunda Fotografía del colaborador Capturada");
        } 
    }//GEN-LAST:event_jButton2_Foto2ActionPerformed

    private void jButton3_Foto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_Foto3ActionPerformed
        // TODO add your handling code here:
        if (manipular_byte != null) {
            persona.setImagen3(manipular_byte);
            JOptionPane.showMessageDialog(null, "Tercera Fotografía del colaborador Capturada");
            Btn_TomaFoto.setEnabled(false);
            jButton_Foto1.setEnabled(false);
            jButton2_Foto2.setEnabled(false);
            jButton3_Foto3.setEnabled(false);
            Panell=null;
            try {
                mostrarImagen(Pan_Foto, imagen1);
            } catch (IOException ex) {
                Logger.getLogger(Pan_Actualizar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3_Foto3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar;
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_TomaFoto;
    private javax.swing.JComboBox<String> Cbx_Departamento;
    private javax.swing.JComboBox<String> Cbx_Funcion;
    private javax.swing.JComboBox<String> Cbx_Supervisor;
    private javax.swing.JLabel Lbl_Funcion;
    private javax.swing.JLabel Lbl_Guion;
    private javax.swing.JLabel Lbl_PriApe;
    private javax.swing.JLabel Lbl_Rut;
    private javax.swing.JLabel Lbl_SegApe;
    private javax.swing.JLabel Lbl_SegNom;
    private javax.swing.JLabel Lbl_Supervisor;
    private javax.swing.JLabel Lbl_Titulo;
    private javax.swing.JPanel Pan_Foto;
    private javax.swing.JTextField Txt_Digito;
    private javax.swing.JTextField Txt_PriApe;
    private javax.swing.JTextField Txt_PriNomn;
    private javax.swing.JTextField Txt_Rut;
    private javax.swing.JTextField Txt_SegApe;
    private javax.swing.JTextField Txt_SegNom;
    private javax.swing.JButton jButton2_Foto2;
    private javax.swing.JButton jButton3_Foto3;
    private javax.swing.JButton jButton_Foto1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_PRiNomn;
    // End of variables declaration//GEN-END:variables

private void llenaComboDepto() {
        //Completa la información de los departamentos existentes en el sistema
        ArrayList<String> lista = new ArrayList<>(); 
        lista = sQL_Metodos.llenaDepartamento();
        Cbx_Departamento.addItem("");
        for (int i=0; i<lista.size();i++){
            Cbx_Departamento.addItem(lista.get(i));
        }
    }
}
