/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author neyra
 */
public class Pan_ReporteDiario extends javax.swing.JPanel {

    /**
     * Creates new form Pan_ReporteDiario
     */
    public Pan_ReporteDiario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_fecha = new javax.swing.JLabel();
        Dtp_fecha = new com.toedter.calendar.JDateChooser();
        Rbn_todo = new javax.swing.JRadioButton();
        Rbn_atrasos = new javax.swing.JRadioButton();
        Btn_generar = new javax.swing.JButton();
        Btn_imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_reporte = new javax.swing.JTable();

        Lbl_fecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_fecha.setText("Fecha:");
        Lbl_fecha.setToolTipText("");

        Rbn_todo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Rbn_todo.setText("Todo");

        Rbn_atrasos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Rbn_atrasos.setText("Atrasos");

        Btn_generar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_generar.setText("Generar Reporte");

        Btn_imprimir.setIcon(new javax.swing.ImageIcon("C:\\Users\\neyra\\Documents\\CFT San Agustin\\3 Semestre\\APR038 - Práctica Intermedia\\Proyecto\\Codigo2\\RelojControl\\src\\Resources\\printer.png")); // NOI18N

        Tbl_reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RUT", "Nombre", "Apellido", "Departamento", "Hora de Entrada", "Hora de Salida"
            }
        ));
        jScrollPane1.setViewportView(Tbl_reporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dtp_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Rbn_todo)
                .addGap(66, 66, 66)
                .addComponent(Rbn_atrasos)
                .addGap(56, 56, 56)
                .addComponent(Btn_generar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(Btn_imprimir)
                .addGap(47, 47, 47))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Btn_imprimir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dtp_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Lbl_fecha)
                                .addComponent(Rbn_todo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Rbn_atrasos)
                                .addComponent(Btn_generar)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_generar;
    private javax.swing.JButton Btn_imprimir;
    private com.toedter.calendar.JDateChooser Dtp_fecha;
    private javax.swing.JLabel Lbl_fecha;
    private javax.swing.JRadioButton Rbn_atrasos;
    private javax.swing.JRadioButton Rbn_todo;
    private javax.swing.JTable Tbl_reporte;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
