/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BD.Funciones;
import static BD.Funciones.Panell;
import static BD.Funciones.mostrarImagen;
import static BD.Funciones.startCamera;
//import static BD.Funciones.startCamera;
import BD.SQL_Metodos;
import BD.Persona;
import static BD.Persona.imagen1;
import static BD.Persona.manipular_byte;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.opencv.core.Core;
//import org.opencv.core.Core;

/**
 *
 * @author neyra
 */
public class Pan_Nuevo extends javax.swing.JPanel {
    String rut, digito, pnombre, snombre, papellido, sapellido;
    public SQL_Metodos sQL_Metodos = new SQL_Metodos();
    Persona persona = new Persona();
    /**
     * Creates new form Pan_Nuevo
     */
    public Pan_Nuevo() {
        initComponents();
        Txt_Rut.requestFocus();
        Btn_Cancelar.setEnabled(false);
        Cbx_Departamento.removeAllItems();
        Cbx_Funcion.removeAllItems();
        Btn_foto1.setEnabled(false);
        Btn_foto3.setEnabled(false);
        Btn_foto2.setEnabled(false);
        llenaComboDepto();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Lbl_Rut = new javax.swing.JLabel();
        Txt_Rut = new javax.swing.JTextField();
        Lbl_Guion = new javax.swing.JLabel();
        Txt_Digito = new javax.swing.JTextField();
        Txt_PriNomn = new javax.swing.JTextField();
        Txt_SegNom = new javax.swing.JTextField();
        Txt_PriApe = new javax.swing.JTextField();
        Txt_SegApe = new javax.swing.JTextField();
        lbl_PRiNomn = new javax.swing.JLabel();
        Lbl_SegNom = new javax.swing.JLabel();
        Lbl_PriApe = new javax.swing.JLabel();
        Lbl_SegApe = new javax.swing.JLabel();
        Lbl_Funcion = new javax.swing.JLabel();
        Lbl_Supervisor = new javax.swing.JLabel();
        Cbx_Departamento = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Cbx_Funcion = new javax.swing.JComboBox<>();
        Cbx_Supervisor = new javax.swing.JComboBox<>();
        Pan_Foto = new javax.swing.JPanel();
        Btn_TomaFoto = new javax.swing.JButton();
        Btn_foto1 = new javax.swing.JButton();
        Btn_foto2 = new javax.swing.JButton();
        Btn_foto3 = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1028, 563));

        Lbl_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Lbl_Titulo.setText("Datos de Empleado:");

        Lbl_Rut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Rut.setText("Rut:");

        Txt_Rut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_Rut.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txt_Rut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_RutFocusLost(evt);
            }
        });
        Txt_Rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_RutKeyTyped(evt);
            }
        });

        Lbl_Guion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Guion.setText("-");

        Txt_Digito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_Digito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Txt_Digito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_DigitoFocusLost(evt);
            }
        });
        Txt_Digito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_DigitoKeyTyped(evt);
            }
        });

        Txt_PriNomn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_PriNomn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_PriNomnFocusLost(evt);
            }
        });

        Txt_SegNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Txt_PriApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_PriApe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_PriApeFocusLost(evt);
            }
        });

        Txt_SegApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Txt_SegApe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Txt_SegApeFocusLost(evt);
            }
        });

        lbl_PRiNomn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_PRiNomn.setText("Primer Nombre:");

        Lbl_SegNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_SegNom.setText("Segundo Nombre:");

        Lbl_PriApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_PriApe.setText("Primer Apellido:");

        Lbl_SegApe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_SegApe.setText("Segundo Apellido:");

        Lbl_Funcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Funcion.setText("Función:");

        Lbl_Supervisor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_Supervisor.setText("Supervisor:");

        Cbx_Departamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cbx_Departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cbx_Departamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cbx_DepartamentoItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Departamento:");

        Cbx_Funcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cbx_Funcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cbx_Funcion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cbx_FuncionItemStateChanged(evt);
            }
        });

        Cbx_Supervisor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cbx_Supervisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cbx_Supervisor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cbx_SupervisorItemStateChanged(evt);
            }
        });

        Pan_Foto.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout Pan_FotoLayout = new javax.swing.GroupLayout(Pan_Foto);
        Pan_Foto.setLayout(Pan_FotoLayout);
        Pan_FotoLayout.setHorizontalGroup(
            Pan_FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Pan_FotoLayout.setVerticalGroup(
            Pan_FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        Btn_TomaFoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_TomaFoto.setText("Captura Fotografía");
        Btn_TomaFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TomaFotoActionPerformed(evt);
            }
        });

        Btn_foto1.setText("Foto 1");
        Btn_foto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_foto1ActionPerformed(evt);
            }
        });

        Btn_foto2.setText("Foto 2");
        Btn_foto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_foto2ActionPerformed(evt);
            }
        });

        Btn_foto3.setText("Foto 3");
        Btn_foto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_foto3ActionPerformed(evt);
            }
        });

        Btn_Cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CancelarMouseClicked(evt);
            }
        });

        Btn_Guardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_Guardar.setText("Guardar");
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Titulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(Lbl_Funcion)
                                    .addComponent(Lbl_Supervisor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Cbx_Supervisor, 0, 350, Short.MAX_VALUE)
                                    .addComponent(Cbx_Funcion, 0, 350, Short.MAX_VALUE)
                                    .addComponent(Cbx_Departamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Lbl_PriApe)
                                            .addComponent(Lbl_SegApe))
                                        .addGap(200, 200, 200))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_PRiNomn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Lbl_Rut, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Lbl_SegNom, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Txt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Lbl_Guion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Txt_Digito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Txt_PriNomn)
                                    .addComponent(Txt_SegNom)
                                    .addComponent(Txt_PriApe)
                                    .addComponent(Txt_SegApe))))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_TomaFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Cancelar)
                                .addGap(40, 40, 40)
                                .addComponent(Btn_Guardar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_foto3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Pan_Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pan_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_Guion)
                            .addComponent(Txt_Digito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_Rut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_PriNomn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_PRiNomn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_SegNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_SegNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_PriApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_PriApe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_SegApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_SegApe))))
                .addGap(18, 18, 18)
                .addComponent(Btn_TomaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Cbx_Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_foto1)
                    .addComponent(Btn_foto2)
                    .addComponent(Btn_foto3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Funcion)
                    .addComponent(Cbx_Funcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Supervisor)
                    .addComponent(Cbx_Supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Cancelar)
                    .addComponent(Btn_Guardar))
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_RutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_RutFocusLost

        rut = Txt_Rut.getText();
        int rutInt = Integer.parseInt(rut);
        persona.setRut(rutInt);
        Txt_Rut.setText(Funciones.formateo_Rut(rut));
        Btn_Cancelar.setEnabled(true);

    }//GEN-LAST:event_Txt_RutFocusLost

    private void Txt_DigitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_DigitoFocusLost
        //Calcula y valida el Digito Verificador del RUT
        Txt_Digito.setText(Txt_Digito.getText().toUpperCase());
        rut = Txt_Rut.getText();
        persona.setVerificador(Txt_Digito.getText());
        digito = Funciones.digito(rut);
        if (!Txt_Digito.getText().equals(digito)) {
            JOptionPane.showMessageDialog(this, "RUT ingresado no es valido, favor de verificar los datos");
            Txt_Rut.setText("");
            Txt_Digito.setText("");
            Txt_Rut.requestFocus();
        }

    }//GEN-LAST:event_Txt_DigitoFocusLost

    private void Txt_RutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_RutKeyTyped
        //valida que solo se ingresen números y sognos de puntuación
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57 || key == 44 || key == 46;
        if (!numeros) {
            evt.consume();
        }

    }//GEN-LAST:event_Txt_RutKeyTyped

    private void Txt_DigitoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_DigitoKeyTyped
        //valida que solo se ingresen números y letra K (mayuscula o minuscula)
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57 || key == 75 || key == 107;
        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_Txt_DigitoKeyTyped

    private void Txt_PriNomnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_PriNomnFocusLost
        //Valida que el campo de texto asiciado el Primer Nombre no se encuentre vacio
        pnombre= Txt_PriNomn.getText();		
        if ("".equals(Txt_Digito.getText())){  
            Txt_Digito.requestFocus();
        }
        else{
            if ("".equals(pnombre)){
                JOptionPane.showMessageDialog(this, "Debe ingresar el Primer Nombre del Colaborador");
                Txt_PriNomn.requestFocus();
            }
        }

    }//GEN-LAST:event_Txt_PriNomnFocusLost

    private void Txt_PriApeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_PriApeFocusLost
        //Valida que el campo de texto asiciado el Primer Apellido no se encuentre vacio
        papellido= Txt_PriApe.getText();
	if("".equals(Txt_PriNomn.getText())){
            Txt_PriNomn.requestFocus();
        }
        else{
            if("".equals(papellido)){
                JOptionPane.showMessageDialog(this, "Debe ingresar el Primer Apellido del Colaborador");
                Txt_PriApe.requestFocus();
            }
        }

    }//GEN-LAST:event_Txt_PriApeFocusLost

    private void Txt_SegApeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txt_SegApeFocusLost
        //Valida que el campo de texto asiciado el Segundo Apellido no se encuentre vacio
        sapellido=Txt_SegApe.getText();
	if ("".equals(Txt_PriApe.getText())){
            Txt_PriApe.requestFocus();
        }
        else{
            if ("".equals(sapellido)){
                JOptionPane.showMessageDialog(this, "Debe ingresar el Segundo Apellido del Colaborador");
                Txt_SegApe.requestFocus();
            }
        }

    }//GEN-LAST:event_Txt_SegApeFocusLost

    private void Btn_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CancelarMouseClicked
        //Limpia todo el formulario preparandolo para el ingreso de nueva información
       limpiar();
    }//GEN-LAST:event_Btn_CancelarMouseClicked

    private void Cbx_DepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cbx_DepartamentoItemStateChanged
        //Llena la información de los Combobox de cargos y supervisores según el departamento seleccionado
        ArrayList<String> cargo = new ArrayList<>();
        ArrayList<String> supervisor = new ArrayList<>();
        Cbx_Funcion.removeAllItems();
        Cbx_Funcion.addItem("");
        Cbx_Supervisor.removeAllItems();
        Cbx_Supervisor.addItem("");
        String aux;
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (Cbx_Departamento.getSelectedIndex() > 0) {
                aux = Cbx_Departamento.getSelectedItem().toString();
                cargo = sQL_Metodos.llenaCargo(aux);
                for (int i = 0; i < cargo.size(); i++) {
                    Cbx_Funcion.addItem(cargo.get(i));
                }
                supervisor = sQL_Metodos.llenaSupervisor(aux);
                for (int i = 0; i < supervisor.size(); i++) {
                    Cbx_Supervisor.addItem(supervisor.get(i));
                }
                // Asigna el idDepartamento al objeto persona
                persona.setIdDepartamento(sQL_Metodos.getIdDepartamento(Cbx_Departamento.getSelectedItem().toString()));
                System.out.println("Persona.idDepartamento = "+ persona.getIdDepartamento());
            }
        }

    }//GEN-LAST:event_Cbx_DepartamentoItemStateChanged

private void Btn_TomaFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TomaFotoActionPerformed
    System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    startCamera();
    Panell = Pan_Foto;
    Btn_foto1.setEnabled(true);
    Btn_foto3.setEnabled(true);
    Btn_foto2.setEnabled(true);
    }//GEN-LAST:event_Btn_TomaFotoActionPerformed

    private void Btn_foto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_foto1ActionPerformed

        if (manipular_byte != null) {
            persona.setImagen1(manipular_byte);
            JOptionPane.showMessageDialog(null, "Primera Fotografía del colaborador Capturada");
        }

    }//GEN-LAST:event_Btn_foto1ActionPerformed

    private void Btn_foto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_foto2ActionPerformed

        if (manipular_byte != null) {
            persona.setImagen2(manipular_byte);
            JOptionPane.showMessageDialog(null, "Segunda Fotografía del colaborador Capturada");
        }

    }//GEN-LAST:event_Btn_foto2ActionPerformed

    private void Btn_foto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_foto3ActionPerformed

        if (manipular_byte != null) {
            persona.setImagen3(manipular_byte);
            JOptionPane.showMessageDialog(null, "Tercera Fotografía del colaborador Capturada");
            Btn_TomaFoto.setEnabled(false);
            Btn_foto1.setEnabled(false);
            Btn_foto2.setEnabled(false);
            Btn_foto3.setEnabled(false);
            Panell=null;
            try {
                mostrarImagen(Pan_Foto, imagen1);
            } catch (IOException ex) {
                Logger.getLogger(Pan_Nuevo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_Btn_foto3ActionPerformed

    private void Cbx_SupervisorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cbx_SupervisorItemStateChanged
        // TODO add your handling code here:
        int aux=Cbx_Supervisor.getSelectedIndex();
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(Cbx_Supervisor.getSelectedIndex()>0){
                if(1<=aux && aux<=8){
                    persona.setSupervisor(sQL_Metodos.getIdSupervisor(Cbx_Supervisor.getSelectedItem().toString(), 1));
                    System.out.println("Persona.Supervisor = "+ persona.getSupervisor());
                }
                if (8<aux){
                    persona.setSupervisor(sQL_Metodos.getIdSupervisor(Cbx_Supervisor.getSelectedItem().toString(), persona.getIdDepartamento()));
                    System.out.println("Persona.Supervisor = "+ persona.getSupervisor());
                }
                
            }
        }
        
    }//GEN-LAST:event_Cbx_SupervisorItemStateChanged

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed
        // TODO add your handling code here:
        persona.setRut(Integer.parseInt(Txt_Rut.getText()));
        persona.setVerificador(Txt_Digito.getText());
        persona.setPrimerNombre(Txt_PriNomn.getText());
        persona.setSegundoNombre(Txt_SegNom.getText());
        persona.setPrimerApellido(Txt_PriApe.getText());
        persona.setSegundoApellido(Txt_SegApe.getText());
        
        /*
        Byte img1 = new Byte(persona.getImagen1());
        Byte img2 = new String(persona.getImagen1());
        Byte img3 = new String(persona.getImagen3());
        */
        
        System.out.println("Estos son los datos de la persona antes de ser enviados a la BD:");
        System.out.println("RUT = "+persona.getRut()+"-"+persona.getVerificador());
        System.out.println("Nombres = "+persona.getPrimerNombre()+" "+persona.getSegundoNombre());
        System.out.println("Apellidos = "+persona.getPrimerApellido()+" "+persona.getSegundoApellido());
        System.out.println("IdDepartamento = "+persona.getIdDepartamento());
        System.out.println("IdCargo = " +persona.getIdCargo());
        System.out.println("IdSupervisor = "+persona.getSupervisor());
        System.out.println("Primera Foto = "+persona.getImagen1());
        System.out.println("Segunda Foto = "+persona.getImagen2());
        System.out.println("Tercera Foto = "+persona.getImagen3());
        
        sQL_Metodos.insertPersona(persona.getRut(), persona.getVerificador(), persona.getPrimerNombre(), 
                persona.getSegundoNombre(), persona.getPrimerApellido(), persona.getSegundoApellido(), 
                persona.getSupervisor(), persona.getImagen1(), persona.getImagen2(), persona.getImagen3(), 
                persona.getIdCargo(), persona.getIdDepartamento());
        
      
       limpiar();
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Cbx_FuncionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cbx_FuncionItemStateChanged
        // Asigna el valor seleccionado al objeto Persona.IdCargo
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(Cbx_Funcion.getSelectedIndex()>0){
                persona.setIdCargo(sQL_Metodos.getIdCargo(Cbx_Funcion.getSelectedItem().toString()));
                System.out.println("Persona.idCargo = "+ persona.getIdCargo());
            }
        }
    }//GEN-LAST:event_Cbx_FuncionItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton Btn_TomaFoto;
    private javax.swing.JButton Btn_foto1;
    private javax.swing.JButton Btn_foto2;
    private javax.swing.JButton Btn_foto3;
    private javax.swing.JComboBox<String> Cbx_Departamento;
    private javax.swing.JComboBox<String> Cbx_Funcion;
    private javax.swing.JComboBox<String> Cbx_Supervisor;
    private javax.swing.JLabel Lbl_Funcion;
    private javax.swing.JLabel Lbl_Guion;
    private javax.swing.JLabel Lbl_PriApe;
    private javax.swing.JLabel Lbl_Rut;
    private javax.swing.JLabel Lbl_SegApe;
    private javax.swing.JLabel Lbl_SegNom;
    private javax.swing.JLabel Lbl_Supervisor;
    private javax.swing.JLabel Lbl_Titulo;
    private javax.swing.JPanel Pan_Foto;
    private javax.swing.JTextField Txt_Digito;
    private javax.swing.JTextField Txt_PriApe;
    private javax.swing.JTextField Txt_PriNomn;
    private javax.swing.JTextField Txt_Rut;
    private javax.swing.JTextField Txt_SegApe;
    private javax.swing.JTextField Txt_SegNom;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_PRiNomn;
    // End of variables declaration//GEN-END:variables

    private void llenaComboDepto() {
        //Completa la información de los departamentos existentes en el sistema
        ArrayList<String> lista = new ArrayList<>(); 
        lista = sQL_Metodos.llenaDepartamento();
        Cbx_Departamento.addItem("");
        for (int i=0; i<lista.size();i++){
            Cbx_Departamento.addItem(lista.get(i));
        }
    }
    
    private void limpiar(){
        Txt_Rut.setText("");
        Txt_Digito.setText("");
        Txt_PriNomn.setText("");
        Txt_SegNom.setText("");
        Txt_PriApe.setText("");
        Txt_SegApe.setText("");
        Cbx_Departamento.removeAllItems();
        Cbx_Funcion.removeAllItems();
        Cbx_Supervisor.removeAllItems();
        llenaComboDepto();
        Txt_Rut.requestFocus();
        Btn_Cancelar.setEnabled(false);
    }
    
    
}
