/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author neyra
 */
public class Pan_ReporteRangoFechas extends javax.swing.JPanel {

    /**
     * Creates new form Pan_ReporteRangoFechas
     */
    public Pan_ReporteRangoFechas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lbl_fecha = new javax.swing.JLabel();
        Dtp_inicial = new com.toedter.calendar.JDateChooser();
        Lbl_separador = new javax.swing.JLabel();
        Dtp_final = new com.toedter.calendar.JDateChooser();
        Rbn_todo = new javax.swing.JRadioButton();
        Rbn_atrasos = new javax.swing.JRadioButton();
        Btn_generar = new javax.swing.JButton();
        Btn_imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_reporte = new javax.swing.JTable();

        Lbl_fecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_fecha.setText("Fecha:");
        Lbl_fecha.setToolTipText("");

        Lbl_separador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lbl_separador.setText("-");
        Lbl_separador.setToolTipText("");

        Rbn_todo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Rbn_todo.setText("Todo");

        Rbn_atrasos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Rbn_atrasos.setText("Atrasos");

        Btn_generar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_generar.setText("Generar Reporte");

        Btn_imprimir.setIcon(new javax.swing.ImageIcon("C:\\Users\\neyra\\Documents\\CFT San Agustin\\3 Semestre\\APR038 - Práctica Intermedia\\Proyecto\\Codigo2\\RelojControl\\src\\Resources\\printer.png")); // NOI18N

        Tbl_reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RUT", "Nombre", "Apellido", "Departamento", "Hora de Entrada", "Hora de Salida"
            }
        ));
        jScrollPane1.setViewportView(Tbl_reporte);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_fecha)
                .addGap(27, 27, 27)
                .addComponent(Dtp_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_separador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Dtp_final, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Rbn_todo)
                .addGap(18, 18, 18)
                .addComponent(Rbn_atrasos)
                .addGap(18, 18, 18)
                .addComponent(Btn_generar)
                .addGap(18, 18, 18)
                .addComponent(Btn_imprimir)
                .addGap(17, 17, 17))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dtp_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Lbl_fecha)
                                .addComponent(Rbn_todo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Rbn_atrasos)
                                .addComponent(Btn_generar))
                            .addComponent(Dtp_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_separador)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Btn_imprimir)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_generar;
    private javax.swing.JButton Btn_imprimir;
    private com.toedter.calendar.JDateChooser Dtp_final;
    private com.toedter.calendar.JDateChooser Dtp_inicial;
    private javax.swing.JLabel Lbl_fecha;
    private javax.swing.JLabel Lbl_separador;
    private javax.swing.JRadioButton Rbn_atrasos;
    private javax.swing.JRadioButton Rbn_todo;
    private javax.swing.JTable Tbl_reporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
